services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: school
      POSTGRES_PASSWORD: school
      POSTGRES_DB: school_live
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:RELEASE.2026-01-31T20-20-33Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - API_PORT=3001
      - MEDIA_SERVICE_URL=http://media:3002
      - MEDIA_INTERNAL_TOKEN=change-me-media-token
      - DATABASE_URL=postgresql://school:school@postgres:5432/school_live?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=change-me-super-secret
      - JWT_EXPIRES_IN=3600
    depends_on:
      - postgres
      - redis
      - minio
      - media

  media:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    command: npm run -w @school-live/api media:start
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - MEDIA_PORT=3002
      - MEDIA_INTERNAL_TOKEN=change-me-media-token
      - MEDIA_S3_ENDPOINT=http://minio:9000
      - MEDIA_S3_REGION=af-south-1
      - MEDIA_S3_ACCESS_KEY=minioadmin
      - MEDIA_S3_SECRET_KEY=minioadmin
      - MEDIA_S3_BUCKET=school-live-media
      - MEDIA_PUBLIC_BASE_URL=http://localhost:9000/school-live-media
    depends_on:
      - minio

  worker:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    command: npm run -w @school-live/api worker:start
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://school:school@postgres:5432/school_live?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=change-me-super-secret
      - JWT_EXPIRES_IN=3600
    depends_on:
      - postgres
      - redis

  web:
    build:
      context: ..
      dockerfile: docker/web.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://api:3001/api
    depends_on:
      - api

volumes:
  postgres_data:
  redis_data:
  minio_data:
